name: Build and Release

on:
  workflow_run:
    workflows: ["Java CI"]
    branches: [ master ]
    types: [ completed ]

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Apache Ant
        run: sudo apt-get install -y ant

      - name: Set Release Version in `build.xml`
        run: |
          ant update-version -Dnew.version="1.0.${{ github.run_number }}"

      - name: Build Project with Ant
        run: ant -noinput -buildfile build.xml release

      - name: Publish Release (GitHub)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git commit -am "Release: 1.0.${{ github.run_number }}"
          git tag "v1.0.${{ github.run_number }}"
          git push origin master --tags
